---
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  # this translates to the name of the statefulset that is created
  name: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "10Gi"
        volumeMode: Filesystem
  resources:
    requests:
      # This is intentionally low to make it work on local k3d clusters.
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2
      memory: 8Gi
  tlsEnabled: true
  # You can set either a version of the db or a specific image name
  # cockroachDBVersion: v23.2.3
  image:
    name: cockroachdb/cockroach:v23.2.3
  # nodes refers to the number of crdb pods that are created
  # via the statefulset
  nodes: 3
  additionalLabels:
    crdb: is-cool
  # affinity is a new API field that is behind a feature gate that is
  # disabled by default.  To enable please see the operator.yaml file.

  # The affinity field will accept any podSpec affinity rule.
  # affinity:
  #   podAntiAffinity:
  #      preferredDuringSchedulingIgnoredDuringExecution:
  #      - weight: 100
  #        podAffinityTerm:
  #          labelSelector:
  #            matchExpressions:
  #            - key: app.kubernetes.io/instance
  #              operator: In
  #              values:
  #              - cockroachdb
  #          topologyKey: kubernetes.io/hostname

  # nodeSelectors used to match against
  # nodeSelector:
  #   worker-pool-name: crdb-workers

---
# the CockroachDB client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb-client-secure
spec:
  replicas: 1
  selector:
    match: labels
    matchLabels:
      app: cockroachdb-client-secure
  template:
    metadata:
      labels:
        app: cockroachdb-client-secure
    spec:
      serviceAccountName: cockroachdb-sa
      containers:
        - name: cockroachdb-client-secure
          image: cockroachdb/cockroach:v23.2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach/cockroach-certs/
          env:
            - name: ROACH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: ROACH_PASSWORD
          command:
            - sleep
            - "2147483648" # 2^31
      terminationGracePeriodSeconds: 0
      volumes:
        - name: client-certs
          projected:
            sources:
              - secret:
                  name: cockroachdb-node
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: cockroachdb-root
                  items:
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256
