---
# This will
# 1. isolate all the kernels from each other, as well as rest of the cluster.
# 2. allow the kernels to access the internet.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internet-access
  namespace: "{{ .Release.Namespace }}-runtime"
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testuser-volume
  namespace: "{{ .Release.Namespace }}-runtime"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

# These deployment is for pulling in the kernel images
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-python-kernel-deployment
  namespace: "{{ .Release.Namespace }}-runtime"
  labels:
    app: example-python-kernel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-python-kernel
  template:
    metadata:
      labels:
        app: example-python-kernel
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: kernel
          image: "{{ .Values.kernelImages.python }}"
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - name: myvolume
              mountPath: /mnt/data
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: testuser-volume

---
# this deployment is for pulling in the kernel images
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-julia-kernel-deployment
  namespace: "{{ .Release.Namespace }}-runtime"
  labels:
    app: example-julia-kernel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-julia-kernel
  template:
    metadata:
      labels:
        app: example-julia-kernel
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: kernel
          image: "{{ .Values.kernelImages.julia }}"
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - name: myvolume
              mountPath: /mnt/data
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: testuser-volume

---
# this deployment is for pulling in the kernel images
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-javascript-kernel-deployment
  namespace: "{{ .Release.Namespace }}-runtime"
  labels:
    app: example-javascript-kernel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-javascript-kernel
  template:
    metadata:
      labels:
        app: example-javascript-kernel
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: kernel
          image: "{{ .Values.kernelImages.javascript }}"
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - name: myvolume
              mountPath: /mnt/data
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: testuser-volume

---
# this deployment is for pulling in the kernel images
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-racket-kernel-deployment
  namespace: "{{ .Release.Namespace }}-runtime"
  labels:
    app: example-racket-kernel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-racket-kernel
  template:
    metadata:
      labels:
        app: example-racket-kernel
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: kernel
          image: "{{ .Values.kernelImages.racket }}"
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - name: myvolume
              mountPath: /mnt/data
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: testuser-volume
