FROM node:20 AS builder

WORKDIR /app
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY ui/package.json ./ui/package.json
COPY api/package.json ./api/package.json

RUN corepack enable
RUN pnpm i

COPY ui ui
COPY api api

WORKDIR /app/ui
RUN pnpm run build

FROM nginx:1.19-alpine AS server

# nginx conf
# Need to quote the EOF to prevent variable expansion
COPY <<"EOF" /etc/nginx/conf.d/default.conf
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # absolute_redirect off;
    # port_in_redirect off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # try_files $uri /index.html;
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
EOF

# replace GOOGLE_CLIENT_ID from env. This env.sh should be automatically called
# before nginx is fired up.
COPY <<"EOF" /docker-entrypoint.d/env.sh
cp -f /usr/share/nginx/html/index.html /tmp

sed -i -e "s|REPLACE_GOOGLE_CLIENT_ID|$VITE_APP_GOOGLE_CLIENT_ID|g" /tmp/index.html
sed -i -e "s|REPLACE_READ_ONLY|$VITE_APP_READ_ONLY|g" /tmp/index.html
sed -i -e "s|REPLACE_BANNER|$VITE_APP_BANNER|g" /tmp/index.html

cat /tmp/index.html > /usr/share/nginx/html/index.html
EOF

# fix the permission of this file
RUN chmod +x /docker-entrypoint.d/env.sh

# https://stackoverflow.com/questions/45598779/react-router-browserrouter-leads-to-404-not-found-nginx-error-when-going-to
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/ui/dist /usr/share/nginx/html
# COPY --from=builder /app/ui/dist /usr/local/apache2/htdocs/
# CMD ["sh", "-c", "cd /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
