srcDir: "/path/to/codepod-cloud/src/dir"
googleClientId:
# openssl rand -base64 12
jwtSecret: 
READ_ONLY: false
BANNER:
# S3 config
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
AWS_REGION: us-west-1
S3_BUCKET:
kernelImages:
  python: lihebi/codepod-kernel-python:0.5.1-alpha.2
  julia: lihebi/codepod-kernel-julia:0.5.1-alpha.2
  javascript: lihebi/codepod-kernel-javascript:0.5.1-alpha.2
  racket: lihebi/codepod-kernel-racket:0.5.1-alpha.2
