srcDir: "/path/to/codepod-cloud/src/dir"
googleClientId:
# openssl rand -base64 12
jwtSecret: 
READ_ONLY: false
BANNER:
host:
kernelImages:
  python: lihebi/codepod-kernel-python:0.5.1-alpha.2
  julia: lihebi/codepod-kernel-julia:0.5.1-alpha.2
  javascript: lihebi/codepod-kernel-javascript:0.5.1-alpha.2
  racket: lihebi/codepod-kernel-racket:0.5.1-alpha.2
