apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysecret
stringData:
  DATABASE_URL: "{{ .Values.databaseUrl }}"
  JWT_SECRET: "{{ .Values.jwtSecret }}"
  GOOGLE_CLIENT_ID: "{{ .Values.googleClientId }}"
